# Generated by Django 4.2.7 on 2025-11-17 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Webhook URL', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('event_type', models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('product.deleted', 'Product Deleted')], help_text='Event type to trigger webhook', max_length=50)),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='Whether webhook is enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'webhooks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='webhooks_event_t_3d1bb2_idx'), models.Index(fields=['enabled'], name='webhooks_enabled_3de2d1_idx'), models.Index(fields=['-created_at'], name='webhooks_created_02c5fc_idx')],
                'unique_together': {('url', 'event_type')},
            },
        ),
    ]
