# Generated by Django 4.2.7 on 2025-11-17 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('total_records', models.IntegerField(default=0, help_text='Total number of records')),
                ('processed_records', models.IntegerField(default=0, help_text='Number of records processed')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'import_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Product name', max_length=255)),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit (case-insensitive, unique)', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Whether the product is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sku'], name='products_sku_fe2039_idx'), models.Index(fields=['name'], name='products_name_6f9890_idx'), models.Index(fields=['active'], name='products_active_20e15c_idx'), models.Index(fields=['-created_at'], name='products_created_a77fb9_idx')],
            },
        ),
    ]
