# Generated by Django 4.2.7 on 2025-11-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='file_content',
            field=models.TextField(blank=True, help_text='CSV file content stored in database for worker access', null=True),
        ),
    ]
