# Generated by Django 4.2.7 on 2025-11-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_importjob_file_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importjob',
            name='file_content',
        ),
    ]
